// <auto-generated />
using System;
using BetTime.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetTime.Data.Migrations
{
    [DbContext(typeof(BetTimeContext))]
    partial class BetTimeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BetTime.Models.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<decimal>("Odds")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Prediction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("Won")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("BetTime.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "LaLiga",
                            SportId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bundesliga",
                            SportId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Premier League",
                            SportId = 1
                        });
                });

            modelBuilder.Entity("BetTime.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AwayOdds")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<double>("AwayWinProbability")
                        .HasColumnType("float");

                    b.Property<int>("CurrentMinute")
                        .HasColumnType("int");

                    b.Property<decimal>("DrawOdds")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("DrawProbability")
                        .HasColumnType("float");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<decimal>("HomeOdds")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<double>("HomeWinProbability")
                        .HasColumnType("float");

                    b.Property<bool>("IsLive")
                        .HasColumnType("bit");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayOdds = 4.0m,
                            AwayScore = 0,
                            AwayTeamId = 2,
                            AwayWinProbability = 0.0,
                            CurrentMinute = 0,
                            DrawOdds = 3.2m,
                            DrawProbability = 0.0,
                            DurationMinutes = 90,
                            Finished = false,
                            HomeOdds = 1.8m,
                            HomeScore = 0,
                            HomeTeamId = 1,
                            HomeWinProbability = 0.0,
                            IsLive = false,
                            LeagueId = 1,
                            StartTime = new DateTime(2025, 12, 9, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AwayOdds = 5.0m,
                            AwayScore = 0,
                            AwayTeamId = 7,
                            AwayWinProbability = 0.0,
                            CurrentMinute = 0,
                            DrawOdds = 3.5m,
                            DrawProbability = 0.0,
                            DurationMinutes = 90,
                            Finished = false,
                            HomeOdds = 1.5m,
                            HomeScore = 0,
                            HomeTeamId = 6,
                            HomeWinProbability = 0.0,
                            IsLive = false,
                            LeagueId = 2,
                            StartTime = new DateTime(2025, 12, 9, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AwayOdds = 3.5m,
                            AwayScore = 0,
                            AwayTeamId = 12,
                            AwayWinProbability = 0.0,
                            CurrentMinute = 0,
                            DrawOdds = 3.0m,
                            DrawProbability = 0.0,
                            DurationMinutes = 90,
                            Finished = false,
                            HomeOdds = 2.0m,
                            HomeScore = 0,
                            HomeTeamId = 11,
                            HomeWinProbability = 0.0,
                            IsLive = false,
                            LeagueId = 3,
                            StartTime = new DateTime(2025, 12, 9, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BetTime.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fútbol"
                        });
                });

            modelBuilder.Entity("BetTime.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeagueId = 1,
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 2,
                            LeagueId = 1,
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 3,
                            LeagueId = 1,
                            Name = "Atlético Madrid"
                        },
                        new
                        {
                            Id = 4,
                            LeagueId = 1,
                            Name = "Sevilla"
                        },
                        new
                        {
                            Id = 5,
                            LeagueId = 1,
                            Name = "Valencia"
                        },
                        new
                        {
                            Id = 6,
                            LeagueId = 2,
                            Name = "Bayern Munich"
                        },
                        new
                        {
                            Id = 7,
                            LeagueId = 2,
                            Name = "Borussia Dortmund"
                        },
                        new
                        {
                            Id = 8,
                            LeagueId = 2,
                            Name = "RB Leipzig"
                        },
                        new
                        {
                            Id = 9,
                            LeagueId = 2,
                            Name = "Bayer Leverkusen"
                        },
                        new
                        {
                            Id = 10,
                            LeagueId = 2,
                            Name = "Schalke 04"
                        },
                        new
                        {
                            Id = 11,
                            LeagueId = 3,
                            Name = "Manchester United"
                        },
                        new
                        {
                            Id = 12,
                            LeagueId = 3,
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 13,
                            LeagueId = 3,
                            Name = "Chelsea"
                        },
                        new
                        {
                            Id = 14,
                            LeagueId = 3,
                            Name = "Arsenal"
                        },
                        new
                        {
                            Id = 15,
                            LeagueId = 3,
                            Name = "Manchester City"
                        });
                });

            modelBuilder.Entity("BetTime.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50m,
                            Date = new DateTime(2025, 12, 7, 16, 22, 1, 188, DateTimeKind.Utc).AddTicks(8985),
                            PaymentMethod = "Tarjeta",
                            Type = "DEPOSIT",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 25m,
                            Date = new DateTime(2025, 12, 8, 16, 22, 1, 188, DateTimeKind.Utc).AddTicks(8991),
                            PaymentMethod = "PayPal",
                            Type = "DEPOSIT",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 100m,
                            Date = new DateTime(2025, 12, 6, 16, 22, 1, 188, DateTimeKind.Utc).AddTicks(8992),
                            PaymentMethod = "Tarjeta",
                            Type = "DEPOSIT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 50m,
                            Date = new DateTime(2025, 12, 8, 16, 22, 1, 188, DateTimeKind.Utc).AddTicks(8994),
                            PaymentMethod = "PayPal",
                            Type = "WITHDRAW",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 75m,
                            Date = new DateTime(2025, 12, 7, 16, 22, 1, 188, DateTimeKind.Utc).AddTicks(8995),
                            PaymentMethod = "Tarjeta",
                            Type = "DEPOSIT",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Amount = 30m,
                            Date = new DateTime(2025, 12, 8, 16, 22, 1, 188, DateTimeKind.Utc).AddTicks(8996),
                            PaymentMethod = "PayPal",
                            Type = "WITHDRAW",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BetTime.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 100m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "juan@example.com",
                            Password = "pass123",
                            Role = "user",
                            Username = "juan123"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 150m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "albertoriveiro@hotmail.es",
                            Password = "pass456",
                            Role = "admin",
                            Username = "albertorbd"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 120m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laura@example.com",
                            Password = "pass789",
                            Role = "user",
                            Username = "laura234"
                        });
                });

            modelBuilder.Entity("BetTime.Models.Bet", b =>
                {
                    b.HasOne("BetTime.Models.Match", "Match")
                        .WithMany("Bets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetTime.Models.User", "User")
                        .WithMany("Bets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetTime.Models.League", b =>
                {
                    b.HasOne("BetTime.Models.Sport", "Sport")
                        .WithMany("Leagues")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("BetTime.Models.Match", b =>
                {
                    b.HasOne("BetTime.Models.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetTime.Models.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetTime.Models.League", "League")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");
                });

            modelBuilder.Entity("BetTime.Models.Team", b =>
                {
                    b.HasOne("BetTime.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("BetTime.Models.Transaction", b =>
                {
                    b.HasOne("BetTime.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetTime.Models.League", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("BetTime.Models.Match", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("BetTime.Models.Sport", b =>
                {
                    b.Navigation("Leagues");
                });

            modelBuilder.Entity("BetTime.Models.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");
                });

            modelBuilder.Entity("BetTime.Models.User", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
